name: 3D Contributions

on:
  schedule:
    - cron: "0 */11 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contributions Graph
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIB_GRAPH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: ${{ github.repository_count }}
      - name: Commit & Push
        run: |
          git config user.name TheYoBots
          git config user.email 73843275+TheYoBots@users.noreply.github.com
          git add profile-3d-contrib/profile-night-rainbow.svg
          git mv profile-3d-contrib/profile-night-rainbow.svg github-contrib-graph.svg
          git add github-contrib-graph.svg
          git commit -m "Update 3d Contributions Graph"
          git push --force